// In-memory callable integration harness. Does not replace Firebase emulator testing.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm');
const fs=require('node:fs');
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
function harness(){const storage={};const get=path=>path.split('/').reduce((v,k)=>v?.[k],storage)??null;const set=(path,value)=>{const keys=path.split('/');let v=storage;for(const k of keys.slice(0,-1))v=v[k]||(v[k]={});if(value===null)delete v[keys.at(-1)];else v[keys.at(-1)]=JSON.parse(JSON.stringify(value));};const snap=(value,key)=>({key,val:()=>structuredClone(value),exists:()=>value!==null,forEach:fn=>Object.entries(value||{}).forEach(([k,v])=>fn(snap(v,k)))});const db={ref:path=>({get:async()=>snap(get(path)),transaction:async fn=>{const next=fn(structuredClone(get(path)));if(next===undefined)return {committed:false};set(path,next);return {committed:true,snapshot:snap(next)};},update:async updates=>{for(const [k,v] of Object.entries(updates))set(path+'/'+k,v);}})};const module={exports:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../index'),'utf8'),{exports:module.exports,require:name=>{if(name==='firebase-admin/app')return {initializeApp(){}};if(name==='firebase-admin/database')return {getDatabase:()=>db};if(name==='firebase-functions/v2/https')return {HttpsError,onCall:(opts,fn)=>fn};if(name==='firebase-functions/v2/scheduler')return {onSchedule:(opts,fn)=>fn};if(name==='./engine')return require('../engine');return require(name);},console,Date});return {request:(uid,data)=>module.exports.game({auth:uid?{uid}:null,data}),storage};}
test('two independent identities create, join, start and submit concurrently',async()=>{const h=harness();const {code}=await h.request('alice',{action:'create',name:'Alice'});await h.request('bob',{action:'join',code,name:'Bob'});await h.request('alice',{action:'start',code});const r=h.storage.rooms[code];const payload={action:'answer',code,round:0,gameId:r.public.gameId,choice:r.private.deck[0].correct};await Promise.all([h.request('alice',payload),h.request('bob',payload)]);assert.equal(Object.keys(h.storage.rooms[code].private.answers[0]).length,2);assert.equal(h.storage.rooms[code].public.players.alice.score,0);h.storage.rooms[code].public.deadline=Date.now()-1;await h.request('bob',{action:'sync',code});assert.equal(h.storage.rooms[code].public.players.alice.score,100);assert.equal(h.storage.rooms[code].public.players.bob.score,100);});
test('unauthenticated, nonmember, malformed code, host impersonation rejected',async()=>{const h=harness();await assert.rejects(h.request(null,{action:'create',name:'N'}),e=>e.code==='unauthenticated');const {code}=await h.request('a',{action:'create',name:'A'});await assert.rejects(h.request('b',{action:'start',code}),e=>e.code==='permission-denied');await assert.rejects(h.request('a',{action:'join',code:'../../'}),e=>e.code==='invalid-argument');await h.request('b',{action:'join',code,name:'B'});await assert.rejects(h.request('b',{action:'start',code}),e=>e.code==='permission-denied');});
test('creation and request limits enforced',async()=>{const h=harness();const {code}=await h.request('a',{action:'create',name:'A'});await assert.rejects(h.request('a',{action:'create',name:'A'}),e=>e.code==='resource-exhausted');for(let i=0;i<58;i++)await h.request('a',{action:'sync',code});await assert.rejects(h.request('a',{action:'sync',code}),e=>e.code==='resource-exhausted');});
