const {test}=require('node:test');
const assert=require('node:assert/strict');
const {create,apply,advance,deck,TTL_MS}=require('../engine');
const bank=require('../bank');
const T=1000000;
function setup(){let r=create('host','Alex',T);r=apply(r,'guest','join',{name:'Sam'},T);return apply(r,'host','start',{},T);}
test('five distinct categories and shuffled answer integrity',()=>{for(let n=0;n<50;n++){const d=deck();assert.equal(d.length,5);assert.equal(new Set(d.map(q=>q.category)).size,5);for(const q of d){const source=bank.find(x=>x.id===q.id);assert.equal(q.options[q.correct],source.options[source.correct]);}}});
test('at least two players and host-only start',()=>{let r=create('host','Alex',T);assert.throws(()=>apply(r,'host','start',{},T),/two/);r=apply(r,'guest','join',{name:'Sam'},T);assert.throws(()=>apply(r,'guest','start',{},T),/host/);});
test('answers stay private, no score awarded before reveal, duplicates cannot overwrite',()=>{let r=setup(),q=r.private.deck[0];r=apply(r,'guest','answer',{round:0,gameId:r.public.gameId,choice:q.correct},T+1);assert.equal(r.public.players.guest.score,0);assert.equal(r.public.question.correct,undefined);assert.equal(r.public.result,undefined);assert.equal(r.public.submitted.guest,true);assert.throws(()=>apply(r,'guest','answer',{round:0,gameId:r.public.gameId,choice:(q.correct+1)%4},T+2),/locked/);r=advance(r,T+20000);assert.equal(r.public.players.guest.score,100);assert.equal(r.public.result.outcomes.host.choice,-1);advance(r,T+20001);assert.equal(r.public.players.guest.score,100);});
test('same-answer retry idempotent; exact deadline and stale round/game rejected',()=>{let r=setup(),data={round:0,gameId:r.public.gameId,choice:0};r=apply(r,'guest','answer',data,T+1);r=apply(r,'guest','answer',data,T+2);assert.equal(r.private.answers[0].guest,0);assert.throws(()=>apply(r,'host','answer',data,T+20000),/closed/);assert.throws(()=>apply(r,'host','answer',{...data,round:1},T+1),/closed/);assert.throws(()=>apply(r,'host','answer',{...data,gameId:'old'},T+1),/closed/);});
test('timing advances without host and skips elapsed phases on reconnect',()=>{let r=setup();r=apply(r,'guest','sync',{},T+28000);assert.equal(r.public.round,1);assert.equal(r.public.deadline,T+48000);r=apply(r,'guest','sync',{},T+140000);assert.equal(r.public.status,'finished');assert.equal(r.public.deadline,undefined);});
test('five rounds score 500, shared rankings possible, rematch resets',()=>{let r=setup();for(let i=0;i<5;i++){const time=T+i*28000;for(const uid of ['host','guest'])r=apply(r,uid,'answer',{round:i,gameId:r.public.gameId,choice:r.private.deck[i].correct},time+1);r=advance(r,time+20000);assert.equal(r.public.players.host.score,(i+1)*100);assert.equal(r.public.players.guest.score,(i+1)*100);r=advance(r,time+28000);}r=apply(r,'host','sync',{},T+140000);r=apply(r,'guest','sync',{},T+140000);const old=r.public.gameId;r=apply(r,'host','rematch',{},T+140001);assert.equal(r.public.players.host.score,0);assert.equal(r.public.round,0);assert.notEqual(r.public.gameId,old);});
test('rejoin permitted mid-game only for existing player',()=>{let r=setup();assert.doesNotThrow(()=>apply(r,'guest','join',{name:'Ignored'},T+100));assert.throws(()=>apply(r,'new','join',{name:'New'},T+100),/started/);assert.throws(()=>apply(r,'new','sync',{},T+100),/first/);});
test('names, capacity, expiry, invalid answers enforced',()=>{assert.throws(()=>create('h','   ',T),/1–20/);let r=create('h','Alex',T);assert.throws(()=>apply(r,'g','join',{name:'aLeX'},T),/taken/);for(let i=0;i<11;i++)r=apply(r,'g'+i,'join',{name:'Player '+i},T);assert.throws(()=>apply(r,'overflow','join',{name:'Overflow'},T),/full/);assert.throws(()=>apply(r,'h','sync',{},T+TTL_MS),/expired/);r=setup();assert.throws(()=>apply(r,'host','answer',{round:0,gameId:r.public.gameId,choice:4},T),/four/);});
test('host recovery after 45 seconds, but not while host active',()=>{let r=setup();assert.throws(()=>apply(r,'guest','claimHost',{},T+100),/still/);r=apply(r,'guest','claimHost',{},T+45000);assert.equal(r.public.host,'guest');});
test('Realtime Database empty maps omitted: first answer and reveal still work',()=>{let r=setup();delete r.private.answers;delete r.public.submitted;r=apply(r,'guest','answer',{round:0,gameId:r.public.gameId,choice:0},T+1);assert.equal(r.private.answers[0].guest,0);r=setup();delete r.private.answers;advance(r,T+20000);assert.equal(r.public.players.guest.score,0);});
